version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Test
          command: |
            set -e
            poetry install --with test --sync
            poetry run python --version
            
            mkdir test-results
            poetry run python -m pytest test --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results

workflows:
  main:
    jobs:
      - build-and-test